server:
  port: 8882
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: wcw231407
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: cloudstudy-auth
